### ISSUE TITLE
versions 1.0.8 - 1.0.10 break semver

### ISSUE THREAD

**Issue by njaard** [liborty/medians#1]
Thanks for the library! It's very useful

In https://github.com/liborty/medians/commit/656c508053c0f30233b901100e5e10dab6af5d25 you changed all the functions of the `Median` trait so that they return `Result`s, which [breaks semver](https://doc.rust-lang.org/cargo/reference/semver.html).

I would maybe suggest you yank those versions and republish a version 2.0 of the crate.

**Comment by liborty** [comment]
Thanks for that comment. I was being too economical with issuing major version numbers, as I am actively developing. 
I will do as you suggest and sort it out soon, incorporating some other planned changes into v 2.0 as well.

**Comment by liborty** [comment]
Version 2.0.0 is out now. Sorry it took a while. I took this opportunity of major version to completely rewrite the algorithm and do comparisons. This has resulted in improvements of speed and memory usage. Smaller footprint as well.
