### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Shatur** [liborty/medians#2]
I have the following compilation error:
```
 error[E0599]: no method named `max_1_min_k` found for reference `&[T]` in the current scope
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/medians-2.1.0/src/lib.rs:225:14
    |
225 |         self.max_1_min_k(self.len() / 2 + 1)
    |              ^^^^^^^^^^^ method not found in `&[T]`

error[E0599]: no method named `max_2_min_k` found for reference `&[T]` in the current scope
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/medians-2.1.0/src/lib.rs:233:14
    |
233 |         self.max_2_min_k(self.len() / 2 + 1)
    |              ^^^^^^^^^^^ method not found in `&[T]`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `medians` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```

I use rustc 1.69.0.

**Comment by liborty** [comment]
It looks like it is picking up an old version of `indexvec` crate dependency.
Try `cargo update`?

**Comment by Shatur** [comment]
Right, it was the issue. Updated `indxvec` from 1.4.10 to 1.4.13.

**Comment by liborty** [comment]
You are welcome. I hope you find the fast medians useful.

**Comment by Shatur** [comment]
@liborty just had the same issue with library again. The solution was to update `indxvec` from 1.4.13 to 1.4.15.

I see that you are the author of `indexvec`. Please, don't break semver. If you making a breaking change in the library, it should be a minor version bump instead of a patch version bump.

And in your Cargo.toml in `medians` you set minimal version of `indexvec` to 1.4:
https://github.com/liborty/medians/blob/838e83f88dd51f85dc8e4acc66e474b1a9888059/Cargo.toml#L25
But it's not true, the minimal version is 1.4.15 since you break semver in it.

My recommendation would to bump `indexvec` to 1.5.0, set minimal version in `medians` to `1.5` and next time bump minor version (e.g. to 1.6) after next breaking change. This is how rust libraries usually do.
